### ISSUE TITLE
[docs] Create Readme for Project

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/GTA-VC#1]
With hope of building upon this project as the next favourite VS code theem, we would need more hands. Therefore havibng a detailed Readme would be nice

### ---Headings---
- Intoduction: What the heck is this extension for VS code
- installation: this should show how you can install it using extensions option from teh sidepanel in vs code by searching for ```gta vc```
- Contributing: How to clone this repository, make changes to theme or add new functionalities, package it into a ```vsix``` file and then test locally by pressing ```ctrl + shift + p``` > enter ```Extensions: install from vsix``` > ```select the file```
for more details about this step, refer [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#installation)
- find us: here refer the already existing links in the readme, marketplace and demo

### ---Assets---
to make readme more understandable, we need to attach certain gif's or images, for that create an assets folder and add images there, after that use them. refer [here](https://www.geeksforgeeks.org/how-to-add-images-on-readme-md-file-in-a-github-repository-from-the-local-system/) for help

### Markdown reference
refer [this ](https://stackedit.io/app#)website to get familiar with markdown

**Comment by bhavnisharora** [comment]
I would like to work on this issue

**Comment by himanshu007-creator** [comment]
Solved via #2
